ddconfig:
  ch: 64
  out_ch: 61
  ch_mult: [1, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  attn_heads: 4
  attn_dim_head: 32
  in_channels: 61
  resolution: 64
  z_channels: 4
  double_z: true
lossconfig:
  disc_start: 9999999
  disc_in_channels: 61
  perceptual_weight: 0.0
  kl_weight: 0.000001
  disc_weight: 0.0
  version3d: true
embed_dim: 4
image_key: "fmri"
learning_rate: !!float 2e-4
version3d: true
latent_scale: "minmax_norm"